import LegalLayout from "./LegalLayout";

export default function TermsOfService() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="February 13, 2026">
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your access to and use of
        MyCareerCopilot (&quot;Service&quot;), operated by MyCareerCopilot. By creating
        an account or installing our browser extension, you agree to be bound
        by these Terms.
      </p>

      <h2>1. The Service</h2>
      <p>
        MyCareerCopilot is an AI-assisted career management platform. It
        helps users find relevant job opportunities, tailor application
        materials, prepare for interviews, and explore career paths. A
        companion Chrome extension provides one-click form autofill on
        supported job boards.
      </p>

      <h2>2. Eligibility</h2>
      <p>
        You must be at least 16 years old (or the age of majority in your
        jurisdiction, if higher) to use the Service. By using the Service,
        you represent that you meet this requirement.
      </p>

      <h2>3. Accounts</h2>
      <ul>
        <li>You are responsible for keeping your password confidential.</li>
        <li>You are responsible for all activity that occurs under your account.</li>
        <li>You must notify us immediately of any unauthorized access at <a href="mailto:support@mycareercopilot.ca">support@mycareercopilot.ca</a>.</li>
        <li>One person, one account. You may not share your account credentials.</li>
      </ul>

      <h2>4. Plans, Billing &amp; Subscriptions</h2>
      <h3>4.1 Free tier</h3>
      <p>
        The Free tier includes monthly usage limits on each AI-powered
        feature (e.g., 5 job applications, 5 resume optimizations, 3
        interview prep generations, 2 career path analyses, 5 cover
        letters, 5 Chrome extension uses). Job search and resume upload
        remain unlimited on the Free tier.
      </p>

      <h3>4.2 Pro subscription</h3>
      <ul>
        <li>The Pro plan is offered at US$19.99/month, billed monthly via Stripe.</li>
        <li>Pro removes monthly limits on all features.</li>
        <li>Subscriptions automatically renew at the end of each billing period unless cancelled.</li>
        <li>You can cancel at any time from your Billing page. Access continues until the end of the current billing period.</li>
        <li>Prices may change with 30 days&apos; advance email notice. Continued use after the change constitutes acceptance.</li>
      </ul>

      <h3>4.3 Refunds</h3>
      <p>
        Refunds are governed by our <a href="/refunds">Refund Policy</a>.
      </p>

      <h2>5. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service for any unlawful purpose or in violation of any applicable law</li>
        <li>Submit false, deceptive, or fraudulent information in applications generated by the Service</li>
        <li>Reverse engineer, decompile, or attempt to extract source code from the Service or extension</li>
        <li>Scrape, crawl, or otherwise programmatically access the Service in a way that materially harms its operation</li>
        <li>Resell, redistribute, or commercially exploit the Service without our written permission</li>
        <li>Use the Service to spam employers (e.g., submitting many low-quality applications using auto-generated content the user did not review)</li>
        <li>Attempt to circumvent monthly usage limits</li>
        <li>Upload content that is unlawful, abusive, harassing, defamatory, or that infringes another party&apos;s rights</li>
        <li>Impersonate another person or misrepresent your affiliation</li>
      </ul>

      <h2>6. AI-Generated Content</h2>
      <p>
        The Service produces AI-generated text (resume bullets, cover
        letters, interview prep, career coach replies). You are responsible
        for reviewing every piece of generated content before relying on it
        or sending it to a third party. Generated content may be inaccurate,
        outdated, or unsuitable for your specific context. We make no
        warranty that AI-generated content will land you a job, an
        interview, or a particular salary.
      </p>

      <h2>7. Your Content</h2>
      <p>
        You retain ownership of the content you upload (resumes, cover
        letters, notes). By uploading content, you grant us a limited,
        worldwide, royalty-free license to host, process, and display that
        content solely to operate the Service for you. We do not use your
        content to train AI models. We do not share your content with
        employers without your action.
      </p>

      <h2>8. Intellectual Property</h2>
      <p>
        The Service, its UI, code, branding, and content (excluding your
        Content) are owned by MyCareerCopilot and protected by copyright,
        trademark, and other intellectual property laws. These Terms do not
        grant you any rights in our trademarks or branding.
      </p>

      <h2>9. Third-Party Services</h2>
      <p>
        The Service integrates with third parties (Stripe for payments,
        Resend for email, OpenAI and Anthropic for AI, Google for sign-in,
        JSearch for job data). Your use of those services through ours is
        also subject to their own terms. We are not responsible for the
        availability or content of third-party services.
      </p>

      <h2>10. Suspension &amp; Termination</h2>
      <p>
        We may suspend or terminate your account, at our discretion, if you
        violate these Terms, abuse the Service, or for any lawful reason
        with reasonable notice where practicable. You may close your account
        at any time by emailing{" "}
        <a href="mailto:support@mycareercopilot.ca">support@mycareercopilot.ca</a>.
      </p>

      <h2>11. Disclaimers</h2>
      <p>
        The Service is provided &quot;as is&quot; and &quot;as available.&quot; To the maximum
        extent permitted by law, we disclaim all warranties, express or
        implied, including merchantability, fitness for a particular
        purpose, and non-infringement. We do not guarantee that the Service
        will be uninterrupted, error-free, or that AI-generated content
        will be accurate, complete, or suitable for any particular purpose.
      </p>

      <h2>12. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, MyCareerCopilot and its
        officers, employees, and affiliates will not be liable for any
        indirect, incidental, special, consequential, or punitive damages,
        or any loss of profits, revenues, data, or goodwill, arising out of
        or in connection with the Service. Our total aggregate liability
        for any claim arising from these Terms or the Service will not
        exceed the amount you paid us in the 12 months preceding the
        claim, or US$100, whichever is greater.
      </p>

      <h2>13. Indemnification</h2>
      <p>
        You agree to indemnify and hold MyCareerCopilot harmless from any
        claim, demand, or damages arising from your use of the Service in
        violation of these Terms or applicable law.
      </p>

      <h2>14. Governing Law</h2>
      <p>
        These Terms are governed by the laws of the Province of Ontario,
        Canada, and the federal laws of Canada applicable therein, without
        regard to conflict-of-laws principles. Any dispute will be resolved
        in the courts of Ontario unless local consumer protection laws
        require otherwise.
      </p>

      <h2>15. Changes to These Terms</h2>
      <p>
        We may update these Terms from time to time. We will notify you of
        material changes by email at least 14 days before they take effect.
        Continued use of the Service after the effective date constitutes
        acceptance.
      </p>

      <h2>16. Contact</h2>
      <p>
        Questions about these Terms? Email{" "}
        <a href="mailto:support@mycareercopilot.ca">support@mycareercopilot.ca</a>.
      </p>
    </LegalLayout>
  );
}
